# .github/workflows/deploy.yml

name: Deploy AlimAI Bot to Heroku # Workflow এর নাম

on:
  push:
    branches:
      - main # যখন main শাখায় কোড পুশ করা হবে, তখন এটি ট্রিগার হবে।

jobs:
  deploy:
    runs-on: ubuntu-latest # এই Workflow Ubuntu অপারেটিং সিস্টেমে চলবে।

    steps:
    - name: Checkout repository # GitHub রিপোজিটরি থেকে কোড চেকআউট (ডাউনলোড) করে।
      uses: actions/checkout@v4

    - name: Deploy to Heroku # Heroku তে ডিপ্লয় করে।
      uses: akhileshns/heroku-deploy@v3.12.12 # Heroku ডিপ্লয়মেন্ট অ্যাকশন
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # GitHub Secrets থেকে Heroku API Key নেয়।
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # আপনার Heroku অ্যাপের নাম। এটিও GitHub Secrets এ সেট করতে হবে।
        heroku_email: ${{ secrets.HEROKU_EMAIL }}       # আপনার Heroku অ্যাকাউন্টের ইমেইল। এটিও GitHub Secrets এ সেট করতে হবে।
        buildpack: heroku/python                      # Python বিল্ডপ্যাক ব্যবহার করছি।
        branch: main                                  # main শাখা থেকে ডিপ্লয় করছি।
        justlogin: false                              # লগইন করে ডিপ্লয় করবে।
      env:
        # Heroku তে আপনার .env ফাইলের ভেরিয়েবলগুলো সেট করুন।
        # এইগুলোও GitHub Secrets এ সেট করতে হবে।
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
        # আপনার যদি আরও কোনো এনভায়রনমেন্ট ভেরিয়েবল থাকে, এখানে যোগ করুন।